let s:here = expand('<sfile>:p:h')
execute 'source' s:here . '/test_add.vim'
execute 'source' s:here . '/test_branch.vim'
execute 'source' s:here . '/test_checkout.vim'
execute 'source' s:here . '/test_commit.vim'
execute 'source' s:here . '/test_config.vim'
execute 'source' s:here . '/test_diff.vim'
execute 'source' s:here . '/test_log.vim'
execute 'source' s:here . '/test_pull.vim'
execute 'source' s:here . '/test_push.vim'
